/* ------------------------------------------------------------------------------------------------ */
/* -- TABELLE DI ANAGRAFICA DEL MINISTERO DELLA SALUTE (IMPORT CON PERMALINK DA WEB SITE) --------- */
/* ------------------------------------------------------------------------------------------------ */


-- Tabella tipologica delle anagrafiche MdS
CREATE TABLE SPENDING_PHA.MDS_TIPOLOGICA_ANAG
(
	ID            				NUMBER(2)   	 	NOT NULL,
	CODICE                    	VARCHAR2(1)  	 	NOT NULL,
	DESCRIZIONE					VARCHAR2(50)   		NOT NULL
);

-- Comments
COMMENT ON COLUMN SPENDING_PHA.MDS_TIPOLOGICA_ANAG.ID IS 'ID tipologica anagrafica';
COMMENT ON COLUMN SPENDING_PHA.MDS_TIPOLOGICA_ANAG.CODICE IS 'Codice tipologica anagrafica';
COMMENT ON COLUMN SPENDING_PHA.MDS_TIPOLOGICA_ANAG.DESCRIZIONE IS 'Descrizione tipologica anagrafica';

-- Indexes
CREATE UNIQUE INDEX SPENDING_PHA.MDS_TIPOLOGICA_ANAG_PK ON SPENDING_PHA.MDS_TIPOLOGICA_ANAG
(ID);

-- Primary Key
ALTER TABLE SPENDING_PHA.MDS_TIPOLOGICA_ANAG ADD (
  CONSTRAINT MDS_TIPOLOGICA_ANAG_PK
  PRIMARY KEY
  (ID)
  USING INDEX SPENDING_PHA.MDS_TIPOLOGICA_ANAG_PK
  ENABLE VALIDATE);

-- Sequences
CREATE SEQUENCE SPENDING_PHA.SEQ_MDS_TIPOLOGICA_ANAG
  START WITH 1
  MAXVALUE 99
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

-- Triggers
CREATE OR REPLACE TRIGGER SPENDING_PHA.INS_MDS_TIPOLOGICA_ANAG
	 BEFORE INSERT
	 ON SPENDING_PHA.MDS_TIPOLOGICA_ANAG
	 REFERENCING OLD AS OLD NEW AS NEW
	 FOR EACH ROW
BEGIN
	IF :NEW.ID IS NULL THEN
	   SELECT SEQ_MDS_TIPOLOGICA_ANAG.NEXTVAL INTO :NEW.ID FROM DUAL;
	END IF;
END;
/
SHOW ERRORS;



/* ----------------------------------------------------------------------------------------------------- */


-- Tabella tipologica dei Comuni
CREATE TABLE SPENDING_PHA.MDS_A_COMUNE
(
	ID							NUMBER(12)		NOT NULL,
	CODICE                    	NUMBER(6)      	NOT NULL,
	DESCRIZIONE					VARCHAR2(80)   	NOT NULL,
	DATA_INIZIO_VALIDITA		DATE 			NOT NULL,
	DATA_FINE_VALIDITA			DATE
);

-- Comments
COMMENT ON COLUMN SPENDING_PHA.MDS_A_COMUNE.ID IS 'Identificativo del Comune';
COMMENT ON COLUMN SPENDING_PHA.MDS_A_COMUNE.CODICE IS 'Codice ISTAT del Comune';
COMMENT ON COLUMN SPENDING_PHA.MDS_A_COMUNE.DESCRIZIONE IS 'Descrizione del Comune';
COMMENT ON COLUMN SPENDING_PHA.MDS_A_COMUNE.DATA_INIZIO_VALIDITA IS 'Data inizio validità';
COMMENT ON COLUMN SPENDING_PHA.MDS_A_COMUNE.DATA_FINE_VALIDITA IS 'Data fine validità';

-- Indexes
CREATE UNIQUE INDEX SPENDING_PHA.MDS_A_COMUNE_PK ON SPENDING_PHA.MDS_A_COMUNE
(ID);
CREATE UNIQUE INDEX SPENDING_PHA.MDS_A_COMUNE_U_IDX ON SPENDING_PHA.MDS_A_COMUNE
(CODICE, DATA_INIZIO_VALIDITA);

-- Primary Key
ALTER TABLE SPENDING_PHA.MDS_A_COMUNE ADD (
  CONSTRAINT MDS_A_COMUNE_PK
  PRIMARY KEY
  (ID)
  USING INDEX SPENDING_PHA.MDS_A_COMUNE_PK
  ENABLE VALIDATE);
  
-- Constraints
ALTER TABLE SPENDING_PHA.MDS_A_COMUNE ADD 
CONSTRAINT MDS_A_COMUNE_U_IDX 
UNIQUE (CODICE, DATA_INIZIO_VALIDITA) 
USING INDEX MDS_A_COMUNE_U_IDX 
ENABLE VALIDATE;

-- Sequences
CREATE SEQUENCE SPENDING_PHA.SEQ_MDS_A_COMUNE
  START WITH 1
  MAXVALUE 99999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

-- Triggers
CREATE OR REPLACE TRIGGER SPENDING_PHA.INS_MDS_A_COMUNE
	 BEFORE INSERT
	 ON SPENDING_PHA.MDS_A_COMUNE
	 REFERENCING OLD AS OLD NEW AS NEW
	 FOR EACH ROW
BEGIN
	IF :NEW.ID IS NULL THEN
	   SELECT SEQ_MDS_A_COMUNE.NEXTVAL INTO :NEW.ID FROM DUAL;
	END IF;
END;
/
SHOW ERRORS;

/* ----------------------------------------------------------------------------------------------------- */


-- Tabella tipologica delle Province
CREATE TABLE SPENDING_PHA.MDS_A_PROVINCIA
(
	ID							NUMBER(12)		NOT NULL,
	CODICE                    	NUMBER(3)      	NOT NULL,
	DESCRIZIONE					VARCHAR2(30)   	NOT NULL,
	SIGLA                     	VARCHAR2(2)    	NOT NULL,
	DATA_INIZIO_VALIDITA		DATE 			NOT NULL,
	DATA_FINE_VALIDITA			DATE
);

-- Comments
COMMENT ON COLUMN SPENDING_PHA.MDS_A_PROVINCIA.ID IS 'Identificativo della Provincia';
COMMENT ON COLUMN SPENDING_PHA.MDS_A_PROVINCIA.CODICE IS 'Codice ISTAT della Provincia';
COMMENT ON COLUMN SPENDING_PHA.MDS_A_PROVINCIA.DESCRIZIONE IS 'Descrizione della Provincia';
COMMENT ON COLUMN SPENDING_PHA.MDS_A_PROVINCIA.SIGLA IS 'Sigla della Provincia';
COMMENT ON COLUMN SPENDING_PHA.MDS_A_PROVINCIA.DATA_INIZIO_VALIDITA IS 'Data inizio validità';
COMMENT ON COLUMN SPENDING_PHA.MDS_A_PROVINCIA.DATA_FINE_VALIDITA IS 'Data fine validità';

-- Indexes
CREATE UNIQUE INDEX SPENDING_PHA.MDS_A_PROVINCIA_PK ON SPENDING_PHA.MDS_A_PROVINCIA
(ID);
CREATE UNIQUE INDEX SPENDING_PHA.MDS_A_PROVINCIA_U_IDX ON SPENDING_PHA.MDS_A_PROVINCIA
(CODICE, DATA_INIZIO_VALIDITA);

-- Primary Key
ALTER TABLE SPENDING_PHA.MDS_A_PROVINCIA ADD (
  CONSTRAINT MDS_A_PROVINCIA_PK
  PRIMARY KEY
  (ID)
  USING INDEX SPENDING_PHA.MDS_A_PROVINCIA_PK
  ENABLE VALIDATE);
  
-- Constraints
ALTER TABLE SPENDING_PHA.MDS_A_PROVINCIA ADD 
CONSTRAINT MDS_A_PROVINCIA_U_IDX 
UNIQUE (CODICE, DATA_INIZIO_VALIDITA) 
USING INDEX MDS_A_PROVINCIA_U_IDX 
ENABLE VALIDATE;

-- Sequences
CREATE SEQUENCE SPENDING_PHA.SEQ_MDS_A_PROVINCIA
  START WITH 1
  MAXVALUE 99999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

-- Triggers
CREATE OR REPLACE TRIGGER SPENDING_PHA.INS_MDS_A_PROVINCIA
	 BEFORE INSERT
	 ON SPENDING_PHA.MDS_A_PROVINCIA
	 REFERENCING OLD AS OLD NEW AS NEW
	 FOR EACH ROW
BEGIN
	IF :NEW.ID IS NULL THEN
	   SELECT SEQ_MDS_A_PROVINCIA.NEXTVAL INTO :NEW.ID FROM DUAL;
	END IF;
END;
/
SHOW ERRORS;


/* ----------------------------------------------------------------------------------------------------- */


-- Tabella tipologica delle Regioni
CREATE TABLE SPENDING_PHA.MDS_A_REGIONE
(
	ID							NUMBER(12)		NOT NULL,
	CODICE                    	NUMBER(3)      	NOT NULL,
	DESCRIZIONE					VARCHAR2(30)   	NOT NULL,
	DATA_INIZIO_VALIDITA		DATE 			NOT NULL,
	DATA_FINE_VALIDITA			DATE
);

-- Comments
COMMENT ON COLUMN SPENDING_PHA.MDS_A_REGIONE.ID IS 'Identificativo della Regione';
COMMENT ON COLUMN SPENDING_PHA.MDS_A_REGIONE.CODICE IS 'Codice ISTAT della Regione';
COMMENT ON COLUMN SPENDING_PHA.MDS_A_REGIONE.DESCRIZIONE IS 'Descrizione della Regione';
COMMENT ON COLUMN SPENDING_PHA.MDS_A_REGIONE.DATA_INIZIO_VALIDITA IS 'Data inizio validità';
COMMENT ON COLUMN SPENDING_PHA.MDS_A_REGIONE.DATA_FINE_VALIDITA IS 'Data fine validità';

-- Indexes
CREATE UNIQUE INDEX SPENDING_PHA.MDS_A_REGIONE_PK ON SPENDING_PHA.MDS_A_REGIONE
(ID);
CREATE UNIQUE INDEX SPENDING_PHA.MDS_A_REGIONE_U_IDX ON SPENDING_PHA.MDS_A_REGIONE
(CODICE, DATA_INIZIO_VALIDITA);

-- Primary Key
ALTER TABLE SPENDING_PHA.MDS_A_REGIONE ADD (
  CONSTRAINT MDS_A_REGIONE_PK
  PRIMARY KEY
  (ID)
  USING INDEX SPENDING_PHA.MDS_A_REGIONE_PK
  ENABLE VALIDATE);

-- Constraints
ALTER TABLE SPENDING_PHA.MDS_A_REGIONE ADD 
CONSTRAINT MDS_A_REGIONE_U_IDX 
UNIQUE (CODICE, DATA_INIZIO_VALIDITA) 
USING INDEX MDS_A_REGIONE_U_IDX 
ENABLE VALIDATE;
  
-- Sequences
CREATE SEQUENCE SPENDING_PHA.SEQ_MDS_A_REGIONE
  START WITH 1
  MAXVALUE 99999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

-- Triggers
CREATE OR REPLACE TRIGGER SPENDING_PHA.INS_MDS_A_REGIONE
	 BEFORE INSERT
	 ON SPENDING_PHA.MDS_A_REGIONE
	 REFERENCING OLD AS OLD NEW AS NEW
	 FOR EACH ROW
BEGIN
	IF :NEW.ID IS NULL THEN
	   SELECT SEQ_MDS_A_REGIONE.NEXTVAL INTO :NEW.ID FROM DUAL;
	END IF;
END;
/
SHOW ERRORS;


/* ----------------------------------------------------------------------------------------------------- */

-- Tabella tipologica delle nazioni
CREATE TABLE SPENDING_PHA.MDS_A_NAZIONE
(
	ID							NUMBER(12)		NOT NULL,
	CODICE_ISO                	VARCHAR2(2)    	NOT NULL,
	CODICE_ISO_3              	VARCHAR2(3),
	DESCRIZIONE					VARCHAR2(60)   	NOT NULL,
	CODICE_ISTAT              	NUMBER(3),
	DATA_INIZIO_VALIDITA		DATE 		 	NOT NULL,
	DATA_FINE_VALIDITA			DATE
);

-- Comments
COMMENT ON COLUMN SPENDING_PHA.MDS_A_NAZIONE.ID IS 'Identificativo della Nazione';
COMMENT ON COLUMN SPENDING_PHA.MDS_A_NAZIONE.CODICE_ISO IS 'Codice ISO';
COMMENT ON COLUMN SPENDING_PHA.MDS_A_NAZIONE.CODICE_ISO_3 IS 'Codice ISO lunghezza 3';
COMMENT ON COLUMN SPENDING_PHA.MDS_A_NAZIONE.DESCRIZIONE IS 'Nazione';
COMMENT ON COLUMN SPENDING_PHA.MDS_A_NAZIONE.CODICE_ISTAT IS 'Codice ISTAT della Nazione';
COMMENT ON COLUMN SPENDING_PHA.MDS_A_NAZIONE.DATA_INIZIO_VALIDITA IS 'Data inizio validità';
COMMENT ON COLUMN SPENDING_PHA.MDS_A_NAZIONE.DATA_FINE_VALIDITA IS 'Data fine validità';

-- Indexes
CREATE UNIQUE INDEX SPENDING_PHA.MDS_A_NAZIONE_PK ON SPENDING_PHA.MDS_A_NAZIONE
(ID);
CREATE UNIQUE INDEX SPENDING_PHA.MDS_A_NAZIONE_U_IDX ON SPENDING_PHA.MDS_A_NAZIONE
(CODICE_ISO, DATA_INIZIO_VALIDITA);

-- Primary Key
ALTER TABLE SPENDING_PHA.MDS_A_NAZIONE ADD (
  CONSTRAINT MDS_A_NAZIONE_PK
  PRIMARY KEY
  (ID)
  USING INDEX SPENDING_PHA.MDS_A_NAZIONE_PK
  ENABLE VALIDATE);
  
-- Constraints
ALTER TABLE SPENDING_PHA.MDS_A_NAZIONE ADD 
CONSTRAINT MDS_A_NAZIONE_U_IDX 
UNIQUE (CODICE_ISO, DATA_INIZIO_VALIDITA) 
USING INDEX MDS_A_NAZIONE_U_IDX 
ENABLE VALIDATE;

-- Sequences
CREATE SEQUENCE SPENDING_PHA.SEQ_MDS_A_NAZIONE
  START WITH 1
  MAXVALUE 99999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

-- Triggers
CREATE OR REPLACE TRIGGER SPENDING_PHA.INS_MDS_A_NAZIONE
	 BEFORE INSERT
	 ON SPENDING_PHA.MDS_A_NAZIONE
	 REFERENCING OLD AS OLD NEW AS NEW
	 FOR EACH ROW
BEGIN
	IF :NEW.ID IS NULL THEN
	   SELECT SEQ_MDS_A_NAZIONE.NEXTVAL INTO :NEW.ID FROM DUAL;
	END IF;
END;
/
SHOW ERRORS;

 
/* ----------------------------------------------------------------------------------------------------- */
  
  
-- Tabella contenente tutte le anagrafiche del MdS:
-- Strutture pubbliche, private e istituiti penitenziari (Tipo anagrafica: T)
-- ASL (Tipo anagrafica: A)
-- Produttori, Distributori, Grossisti (Tipo anagrafica: P,D)
-- Farmacie (Tipo anagrafica: F)
CREATE TABLE SPENDING_PHA.MDS_ANAG
(
  CODICE                          VARCHAR2(12)      NOT NULL,
  DENOMINAZIONE                   VARCHAR2(255)     NOT NULL,
  PARTITA_IVA                     VARCHAR2(30),
  INDIRIZZO                       VARCHAR2(255),
  CAP                             NUMBER(5),
  FRAZIONE                        VARCHAR2(80),
  ID_COMUNE                   	  NUMBER(12),
  ID_PROVINCIA                    NUMBER(12),
  ID_REGIONE                      NUMBER(12)		NOT NULL,
  TELEFONO                        VARCHAR2(20),
  FAX                             VARCHAR2(20),
  EMAIL                           VARCHAR2(60),
  SITO_WEB                        VARCHAR2(60),
  DATA_INIZIO_VALIDITA            DATE				NOT NULL,
  DATA_FINE_VALIDITA              DATE,
  LATITUDINE                      NUMBER,
  LONGITUDINE                     NUMBER,
  LOCALIZE                        NUMBER(1),
  ID_TIPO_ANAG                    NUMBER(2)         NOT NULL
);


-- Comments
COMMENT ON COLUMN SPENDING_PHA.MDS_ANAG.CODICE IS 'Codice identificativo';
COMMENT ON COLUMN SPENDING_PHA.MDS_ANAG.DENOMINAZIONE IS 'Denominazione';
COMMENT ON COLUMN SPENDING_PHA.MDS_ANAG.PARTITA_IVA IS 'Partita IVA';
COMMENT ON COLUMN SPENDING_PHA.MDS_ANAG.INDIRIZZO IS 'Indirizzo';
COMMENT ON COLUMN SPENDING_PHA.MDS_ANAG.CAP IS 'CAP';
COMMENT ON COLUMN SPENDING_PHA.MDS_ANAG.FRAZIONE IS 'Frazione';
COMMENT ON COLUMN SPENDING_PHA.MDS_ANAG.ID_COMUNE IS 'Identificativo del Comune';
COMMENT ON COLUMN SPENDING_PHA.MDS_ANAG.ID_PROVINCIA IS 'Identificativo della Provincia';
COMMENT ON COLUMN SPENDING_PHA.MDS_ANAG.ID_REGIONE IS 'Identificativo della Regione';
COMMENT ON COLUMN SPENDING_PHA.MDS_ANAG.TELEFONO IS 'Telefono';
COMMENT ON COLUMN SPENDING_PHA.MDS_ANAG.FAX IS 'Fax';
COMMENT ON COLUMN SPENDING_PHA.MDS_ANAG.EMAIL IS 'Email';
COMMENT ON COLUMN SPENDING_PHA.MDS_ANAG.SITO_WEB IS 'Sito web';
COMMENT ON COLUMN SPENDING_PHA.MDS_ANAG.DATA_INIZIO_VALIDITA IS 'Data inizio validità';
COMMENT ON COLUMN SPENDING_PHA.MDS_ANAG.DATA_FINE_VALIDITA IS 'Data fine validità';
COMMENT ON COLUMN SPENDING_PHA.MDS_ANAG.LATITUDINE IS 'Latitudine';
COMMENT ON COLUMN SPENDING_PHA.MDS_ANAG.LONGITUDINE IS 'Longitudine';
COMMENT ON COLUMN SPENDING_PHA.MDS_ANAG.LOCALIZE IS 'Localizzato';
COMMENT ON COLUMN SPENDING_PHA.MDS_ANAG.ID_TIPO_ANAG IS 'ID del tipo di anagrafica';


-- Indexes
CREATE UNIQUE INDEX SPENDING_PHA.MDS_ANAG_PK ON SPENDING_PHA.MDS_ANAG
(CODICE, ID_REGIONE, DATA_INIZIO_VALIDITA, ID_TIPO_ANAG);
CREATE INDEX SPENDING_PHA.MDS_ANAG_ID_T_A_IDX ON SPENDING_PHA.MDS_ANAG
(ID_TIPO_ANAG);

-- Primary Key
ALTER TABLE SPENDING_PHA.MDS_ANAG ADD (
  CONSTRAINT MDS_ANAG_PK
  PRIMARY KEY
  (CODICE, ID_REGIONE, DATA_INIZIO_VALIDITA, ID_TIPO_ANAG)
  USING INDEX SPENDING_PHA.MDS_ANAG_PK
  ENABLE VALIDATE);

-- Foreign Keys
ALTER TABLE SPENDING_PHA.MDS_ANAG ADD (
  CONSTRAINT MDS_ANAG_ID_COM_FK
  FOREIGN KEY (ID_COMUNE)
  REFERENCES SPENDING_PHA.MDS_A_COMUNE (ID)
  ENABLE VALIDATE,
  CONSTRAINT MDS_ANAG_ID_PRV_FK
  FOREIGN KEY (ID_PROVINCIA)
  REFERENCES SPENDING_PHA.MDS_A_PROVINCIA (ID)
  ENABLE VALIDATE,
  CONSTRAINT MDS_ANAG_ID_REG_FK
  FOREIGN KEY (ID_REGIONE)
  REFERENCES SPENDING_PHA.MDS_A_REGIONE (ID)
  ENABLE VALIDATE,
  CONSTRAINT MDS_ANAG_ID_T_ANAG_FK
  FOREIGN KEY (ID_TIPO_ANAG)
  REFERENCES SPENDING_PHA.MDS_TIPOLOGICA_ANAG (ID)
  ENABLE VALIDATE);
