/* ------------------------------------------------------------------------------------------------ */
/* -- TABELLE DI ANAGRAFICA DEL MINISTERO DELLA SALUTE (IMPORT CON PERMALINK DA WEB SITE) --------- */
/* ------------------------------------------------------------------------------------------------ */

-- Drop sequences
DROP SEQUENCE SPENDING_PHA.SEQ_MDS_TIPOLOGICA_ANAG;
DROP SEQUENCE SPENDING_PHA.SEQ_MDS_A_COMUNE;
DROP SEQUENCE SPENDING_PHA.SEQ_MDS_A_PROVINCIA;
DROP SEQUENCE SPENDING_PHA.SEQ_MDS_A_REGIONE;
DROP SEQUENCE SPENDING_PHA.SEQ_MDS_A_NAZIONE;


-- Drop tables, indexes and keys
DROP TABLE SPENDING_PHA.MDS_ANAG CASCADE CONSTRAINTS;
DROP TABLE SPENDING_PHA.MDS_A_NAZIONE CASCADE CONSTRAINTS;
DROP TABLE SPENDING_PHA.MDS_A_REGIONE CASCADE CONSTRAINTS;
DROP TABLE SPENDING_PHA.MDS_A_PROVINCIA CASCADE CONSTRAINTS;
DROP TABLE SPENDING_PHA.MDS_A_COMUNE CASCADE CONSTRAINTS;
DROP TABLE SPENDING_PHA.MDS_TIPOLOGICA_ANAG CASCADE CONSTRAINTS;
