CREATE TABLE SPENDING_PHA.MDS_MOV
(
  ID                        VARCHAR2(255 CHAR)  NOT NULL,
  IMPORT_DATE               TIMESTAMP(6),
  ACCOUNT_HOLDER_CODE       VARCHAR2(255 CHAR),
  ACCOUNT_HOLDER_TYPE_CODE  VARCHAR2(255 CHAR),
  AIC                       VARCHAR2(255 CHAR),
  CUSTOMER_CODE             VARCHAR2(255 CHAR),
  CUSTOMER_TYPE_CODE        VARCHAR2(255 CHAR),
  DOCUMENT_NUMBER           VARCHAR2(255 CHAR),
  DOCUMENT_TYPE_CODE        VARCHAR2(255 CHAR),
  EXPIRATION_DATE           DATE,
  LOT                       VARCHAR2(255 CHAR),
  MOVEMENT_CODE             VARCHAR2(255 CHAR),
  QUANTITY                  FLOAT(22),
  RECIPIENT_CODE            VARCHAR2(255 CHAR),
  RECIPIENT_TYPE_CODE       VARCHAR2(255 CHAR),
  SENDER_CODE               VARCHAR2(255 CHAR),
  SENDER_TYPE_CODE          VARCHAR2(255 CHAR),
  TRANSMISSION_DATE_TIME    TIMESTAMP(6),
  VALUE                     FLOAT(22)
);


CREATE UNIQUE INDEX SPENDING_PHA.MDS_MOV_UN ON SPENDING_PHA.MDS_MOV
(DOCUMENT_TYPE_CODE, AIC, LOT, DOCUMENT_NUMBER, TRANSMISSION_DATE_TIME);

CREATE UNIQUE INDEX SPENDING_PHA.MOVEMENTPK ON SPENDING_PHA.MDS_MOV
(ID);

ALTER TABLE SPENDING_PHA.MDS_MOV ADD (
  CONSTRAINT MOVEMENTPK
  PRIMARY KEY
  (ID)
  USING INDEX SPENDING_PHA.MOVEMENTPK
  ENABLE VALIDATE,
  CONSTRAINT MDS_MOV_UN
  UNIQUE (DOCUMENT_TYPE_CODE, AIC, LOT, DOCUMENT_NUMBER, TRANSMISSION_DATE_TIME)
  USING INDEX SPENDING_PHA.MDS_MOV_UN
  ENABLE VALIDATE);