-- Al termine delle insert è necessario portare il valore corrente della sequence costruita su ID al valore massimo
SET DEFINE OFF;
Insert into SPENDING_PHA.MDS_TIPOLOGICA_ANAG
   (ID, CODICE, DESCRIZIONE)
 Values
   (17, 'F', 'FARMACIA SUCCURSALE');
Insert into SPENDING_PHA.MDS_TIPOLOGICA_ANAG
   (ID, CODICE, DESCRIZIONE)
 Values
   (18, 'F', 'FARMACIA DISPENSARIO');
Insert into SPENDING_PHA.MDS_TIPOLOGICA_ANAG
   (ID, CODICE, DESCRIZIONE)
 Values
   (19, 'F', 'FARMACIA DISPENSARIO STAGIONALE');
Insert into SPENDING_PHA.MDS_TIPOLOGICA_ANAG
   (ID, CODICE, DESCRIZIONE)
 Values
   (1, 'P', 'PRODUTTORE');
Insert into SPENDING_PHA.MDS_TIPOLOGICA_ANAG
   (ID, CODICE, DESCRIZIONE)
 Values
   (2, 'D', 'DEPOSITARIO');
Insert into SPENDING_PHA.MDS_TIPOLOGICA_ANAG
   (ID, CODICE, DESCRIZIONE)
 Values
   (3, 'D', 'GROSSISTA');
Insert into SPENDING_PHA.MDS_TIPOLOGICA_ANAG
   (ID, CODICE, DESCRIZIONE)
 Values
   (4, 'S', 'SMALTITORE');
Insert into SPENDING_PHA.MDS_TIPOLOGICA_ANAG
   (ID, CODICE, DESCRIZIONE)
 Values
   (5, 'F', 'FARMACIA ORDINARIA');
Insert into SPENDING_PHA.MDS_TIPOLOGICA_ANAG
   (ID, CODICE, DESCRIZIONE)
 Values
   (6, 'I', 'IPZS');
Insert into SPENDING_PHA.MDS_TIPOLOGICA_ANAG
   (ID, CODICE, DESCRIZIONE)
 Values
   (7, 'U', 'USCITA');
Insert into SPENDING_PHA.MDS_TIPOLOGICA_ANAG
   (ID, CODICE, DESCRIZIONE)
 Values
   (8, 'Z', 'ALTRO');
Insert into SPENDING_PHA.MDS_TIPOLOGICA_ANAG
   (ID, CODICE, DESCRIZIONE)
 Values
   (9, 'A', 'ASL');
Insert into SPENDING_PHA.MDS_TIPOLOGICA_ANAG
   (ID, CODICE, DESCRIZIONE)
 Values
   (10, 'R', 'REGIONE');
Insert into SPENDING_PHA.MDS_TIPOLOGICA_ANAG
   (ID, CODICE, DESCRIZIONE)
 Values
   (11, 'T', 'STRUTTURA RICOVERO PUBBLICA');
Insert into SPENDING_PHA.MDS_TIPOLOGICA_ANAG
   (ID, CODICE, DESCRIZIONE)
 Values
   (12, 'T', 'STRUTTURA RICOVERO PRIVATA');
Insert into SPENDING_PHA.MDS_TIPOLOGICA_ANAG
   (ID, CODICE, DESCRIZIONE)
 Values
   (13, 'T', 'ISTITUTO PENITENZIARIO');
Insert into SPENDING_PHA.MDS_TIPOLOGICA_ANAG
   (ID, CODICE, DESCRIZIONE)
 Values
   (14, 'L', 'LABORATORIO ANALISI');
Insert into SPENDING_PHA.MDS_TIPOLOGICA_ANAG
   (ID, CODICE, DESCRIZIONE)
 Values
   (15, 'E', 'ESTERO');
Insert into SPENDING_PHA.MDS_TIPOLOGICA_ANAG
   (ID, CODICE, DESCRIZIONE)
 Values
   (16, 'C', 'ESERCIZIO COMMERCIALE');
COMMIT;
