-- Al termine delle insert è necessario portare il valore corrente della sequence costruita su ID al valore massimo
SET DEFINE OFF;
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (1, 'AF', 'AFG', 'AFGHANISTAN', 301, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (2, 'AL', 'ALB', 'ALBANIA', 201, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (3, 'DZ', 'DZA', 'ALGERIA', 401, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (4, 'AD', 'AND', 'ANDORRA', 202, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (5, 'AO', 'AGO', 'ANGOLA', 402, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (6, 'AI', 'AIA', 'ANGUILLA', 502, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (7, 'AQ', 'ATA', 'ANTARTIDE', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (8, 'AG', 'ATG', 'ANTIGUA E BARBUDA', 503, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (9, 'AN', 'ANT', 'ANTILLE OLANDESI', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (10, 'SA', 'SAU', 'ARABIA SAUDITA', 302, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (11, 'AR', 'ARG', 'ARGENTINA', 602, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (12, 'AM', 'ARM', 'ARMENIA', 358, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (13, 'AW', 'ABW', 'ARUBA', 603, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (14, 'AU', 'AUS', 'AUSTRALIA', 701, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (15, 'AT', 'AUT', 'AUSTRIA', 203, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (16, 'AZ', 'AZE', 'AZERBAIJAN', 359, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (17, 'BS', 'BHS', 'BAHAMAS', 505, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (18, 'BH', 'BHR', 'BAHRAIN', 304, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (19, 'BD', 'BGD', 'BANGLADESH', 305, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (20, 'BB', 'BRB', 'BARBADOS', 506, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (21, 'BE', 'BEL', 'BELGIO', 206, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (22, 'BZ', 'BLZ', 'BELIZE', 507, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (23, 'BJ', 'BEN', 'BENIN', 406, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (24, 'BM', 'BMU', 'BERMUDA', 508, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (25, 'BT', 'BTN', 'BHUTAN', 306, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (26, 'BY', 'BLR', 'BIELORUSSIA', 256, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (27, 'BO', 'BOL', 'BOLIVIA', 604, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (28, 'BA', 'BIH', 'BOSNIA ERZEGOVINA', 252, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (29, 'BW', 'BWA', 'BOTSWANA', 408, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (30, 'BR', 'BRA', 'BRASILE', 605, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (31, 'BN', 'BRN', 'BRUNEI DARUSSALAM', 309, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (32, 'BG', 'BGR', 'BULGARIA', 209, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (33, 'BF', 'BFA', 'BURKINA FASO', 409, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (34, 'BI', 'BDI', 'BURUNDI', 410, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (35, 'KH', 'KHM', 'CAMBOGIA', 310, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (36, 'CM', 'CMR', 'CAMERUN', 411, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (37, 'CA', 'CAN', 'CANADA', 509, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (38, 'CV', 'CPV', 'CAPO VERDE', 413, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (39, 'TD', 'TCD', 'CIAD', 415, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (40, 'CL', 'CHL', 'CILE', 606, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (41, 'CN', 'CHN', 'CINA', 314, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (42, 'CY', 'CYP', 'CIPRO', 315, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (43, 'VA', 'VAT', 'CITTÀ DEL VATICANO', 246, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (44, 'CO', 'COL', 'COLOMBIA', 608, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (45, 'KM', 'COM', 'COMORE', 417, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (46, 'KP', 'PRK', 'COREA DEL NORD', 319, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (47, 'KR', 'KOR', 'COREA DEL SUD', 320, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (48, 'CI', 'CIV', 'COSTA D''AVORIO', 404, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (49, 'CR', 'CRI', 'COSTA RICA', 513, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (50, 'HR', 'HRV', 'CROAZIA', 250, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (51, 'CU', 'CUB', 'CUBA', 514, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (52, 'DK', 'DNK', 'DANIMARCA', 212, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (53, 'DM', 'DMA', 'DOMINICA', 515, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (54, 'EC', 'ECU', 'ECUADOR', 609, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (55, 'EG', 'EGY', 'EGITTO', 419, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (56, 'IE', 'IRL', 'EIRE', 221, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (57, 'SV', 'SLV', 'EL SALVADOR', 517, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (58, 'AE', 'ARE', 'EMIRATI ARABI UNITI', 322, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (59, 'ER', 'ERI', 'ERITREA', 466, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (60, 'EE', 'EST', 'ESTONIA', 247, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (61, 'ET', 'ETH', 'ETIOPIA', 420, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (62, 'RU', 'RUS', 'FEDERAZIONE RUSSA', 245, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (63, 'FJ', 'FJI', 'FIJI', 703, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (64, 'PH', 'PHL', 'FILIPPINE', 323, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (65, 'FI', 'FIN', 'FINLANDIA', 214, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (66, 'FR', 'FRA', 'FRANCIA', 215, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (67, 'GA', 'GAB', 'GABON', 421, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (68, 'GM', 'GMB', 'GAMBIA', 422, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (69, 'GE', 'GEO', 'GEORGIA', 360, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (70, 'DE', 'DEU', 'GERMANIA', 216, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (71, 'GH', 'GHA', 'GHANA', 423, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (72, 'JM', 'JAM', 'GIAMAICA', 518, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (73, 'JP', 'JPN', 'GIAPPONE', 326, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (74, 'GI', 'GIB', 'GIBILTERRA', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (75, 'DJ', 'DJI', 'GIBUTI', 424, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (76, 'JO', 'JOR', 'GIORDANIA', 327, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (77, 'GR', 'GRC', 'GRECIA', 220, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (78, 'GD', 'GRD', 'GRENADA', 519, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (79, 'GL', 'GRL', 'GROENLANDIA', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (80, 'GP', 'GLP', 'GUADALUPA', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (81, 'GU', 'GUM', 'GUAM', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (82, 'GT', 'GTM', 'GUATEMALA', 523, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (83, 'GG', 'GGY', 'GUERNSEY', 831, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (84, 'GN', 'GIN', 'GUINEA', 425, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (85, 'GQ', 'GNQ', 'GUINEA EQUATORIALE', 427, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (86, 'GW', 'GNB', 'GUINEA-BISSAU', 426, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (87, 'GY', 'GUY', 'GUYANA', 612, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (88, 'GF', 'GUF', 'GUYANA FRANCESE', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (89, 'HT', 'HTI', 'HAITI', 524, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (90, 'HN', 'HND', 'HONDURAS', 525, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (91, 'HK', 'HKG', 'HONG KONG', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (92, 'IN', 'IND', 'INDIA', 330, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (93, 'ID', 'IDN', 'INDONESIA', 331, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (94, 'IR', 'IRN', 'IRAN', 332, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (95, 'IQ', 'IRQ', 'IRAQ', 333, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (96, 'IS', 'ISL', 'ISLANDA', 223, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (97, 'BV', 'BVT', 'ISOLA DI BOUVET', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (98, 'IM', 'ISOLA DI MAN', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (99, 'CX', 'CXR', 'ISOLA DI NATALE', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (100, 'HM', 'HMD', 'ISOLA HEARD E ISOLE MCDONALD', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (101, 'NF', 'NFK', 'ISOLA NORFOLK', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (102, 'KY', 'CYM', 'ISOLE CAYMAN', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (103, 'CC', 'CCK', 'ISOLE COCOS', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (104, 'CK', 'COK', 'ISOLE COOK', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (105, 'FK', 'FLK', 'ISOLE FALKLAND', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (106, 'FO', 'FRO', 'ISOLE FAROE', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (107, 'MP', 'MNP', 'ISOLE MARIANNE SETTENTRIONALI', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (108, 'MH', 'MHL', 'ISOLE MARSHALL', 712, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (109, 'UM', 'UMI', 'ISOLE MINORI DEGLI STATI UNITI D''AMERICA', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (110, 'SB', 'SLB', 'ISOLE SOLOMON', 725, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (111, 'TC', 'TCA', 'ISOLE TURKS E CAICOS', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (112, 'VI', 'VIR', 'ISOLE VERGINI AMERICANE', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (113, 'VG', 'VGB', 'ISOLE VERGINI BRITANNICHE', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (114, 'IL', 'ISR', 'ISRAELE', 334, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (115, 'IT', 'ITA', 'ITALIA', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (116, 'KZ', 'KAZ', 'KAZAKHISTAN', 356, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (117, 'KE', 'KEN', 'KENYA', 428, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (118, 'KG', 'KGZ', 'KIRGHIZISTAN', 361, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (119, 'KI', 'KIR', 'KIRIBATI', 708, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (120, 'XK', 'KOSOVO', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (121, 'KW', 'KWT', 'KUWAIT', 335, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (122, 'LA', 'LAO', 'LAOS', 336, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (123, 'LS', 'LSO', 'LESOTHO', 429, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (124, 'LV', 'LVA', 'LETTONIA', 248, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (125, 'LB', 'LBN', 'LIBANO', 337, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (126, 'LR', 'LBR', 'LIBERIA', 430, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (127, 'LY', 'LBY', 'LIBIA', 431, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (128, 'LI', 'LIE', 'LIECHTENSTEIN', 225, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (129, 'LT', 'LTU', 'LITUANIA', 249, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (130, 'LU', 'LUX', 'LUSSEMBURGO', 226, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (131, 'MO', 'MAC', 'MACAO', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (132, 'MK', 'MKD', 'MACEDONIA', 253, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (133, 'MG', 'MDG', 'MADAGASCAR', 432, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (134, 'MW', 'MWI', 'MALAWI', 434, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (135, 'MV', 'MDV', 'MALDIVE', 339, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (136, 'MY', 'MYS', 'MALESIA', 340, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (137, 'ML', 'MLI', 'MALI', 435, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (138, 'MT', 'MLT', 'MALTA', 227, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (139, 'MA', 'MAR', 'MAROCCO', 436, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (140, 'MQ', 'MTQ', 'MARTINICA', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (141, 'MR', 'MRT', 'MAURITANIA', 437, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (142, 'MU', 'MUS', 'MAURIZIUS', 438, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (143, 'YT', 'MYT', 'MAYOTTE', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (144, 'MX', 'MEX', 'MESSICO', 527, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (145, 'MD', 'MDA', 'MOLDAVIA', 254, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (146, 'MC', 'MCO', 'MONACO', 229, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (147, 'MN', 'MNG', 'MONGOLIA', 341, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (148, 'ME', 'MNE', 'MONTENEGRO', 270, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (149, 'MS', 'MSR', 'MONTSERRAT', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (150, 'MZ', 'MOZ', 'MOZAMBICO', 440, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (151, 'MM', 'MMR', 'MYANMAR', 307, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (152, 'NA', 'NAM', 'NAMIBIA', 441, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (153, 'NR', 'NRU', 'NAURU', 715, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (154, 'NP', 'NPL', 'NEPAL', 342, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (155, 'NI', 'NIC', 'NICARAGUA', 529, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (156, 'NE', 'NER', 'NIGER', 442, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (157, 'NG', 'NGA', 'NIGERIA', 443, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (158, 'NU', 'NIU', 'NIUE', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (159, 'NO', 'NOR', 'NORVEGIA', 231, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (160, 'NC', 'NCL', 'NUOVA CALEDONIA', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (161, 'NZ', 'NZL', 'NUOVA ZELANDA', 719, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (162, 'OM', 'OMN', 'OMAN', 343, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (163, 'NL', 'NLD', 'PAESI BASSI', 232, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (164, 'PK', 'PAK', 'PAKISTAN', 344, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (165, 'PW', 'PLW', 'PALAU', 720, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (166, 'PA', 'PAN', 'PANAMÁ', 530, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (167, 'PG', 'PNG', 'PAPUA NUOVA GUINEA', 721, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (168, 'PY', 'PRY', 'PARAGUAY', 614, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (169, 'PE', 'PER', 'PERU', 615, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (170, 'PN', 'PCN', 'PITCAIRN', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (171, 'PF', 'PYF', 'POLINESIA FRANCESE', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (172, 'PL', 'POL', 'POLONIA', 233, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (173, 'PR', 'PRI', 'PORTO RICO', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (174, 'PT', 'PRT', 'PORTOGALLO', 234, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (175, 'QA', 'QAT', 'QATAR', 345, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (176, 'GB', 'GBR', 'REGNO UNITO', 219, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (177, 'CZ', 'CZE', 'REPUBBLICA CECA', 257, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (178, 'CF', 'CAF', 'REPUBBLICA CENTROAFRICANA', 414, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (179, 'CG', 'COG', 'REPUBBLICA DEL CONGO', 418, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (180, 'CD', 'COD', 'REPUBBLICA DEMOCRATICA DEL CONGO', 463, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (181, 'DO', 'DOM', 'REPUBBLICA DOMINICANA', 516, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (182, 'RE', 'REU', 'REUNION', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (183, 'RO', 'ROU', 'ROMANIA', 235, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (184, 'RW', 'RWA', 'RUANDA', 446, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (185, 'EH', 'ESH', 'SAHARA OCCIDENTALE', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (186, 'KN', 'KNA', 'SAINT KITTS E NEVIS', 534, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (187, 'PM', 'SPM', 'SAINT PIERRE E MIQUELON', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (188, 'VC', 'VCT', 'SAINT VINCENT E GRENADINE', 533, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (189, 'WS', 'WSM', 'SAMOA', 727, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (190, 'AS', 'ASM', 'SAMOA AMERICANE', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (191, 'SM', 'SMR', 'SAN MARINO', 236, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (192, 'LC', 'LCA', 'SANTA LUCIA', 532, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (193, 'SH', 'SHN', 'SANT''ELENA', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (194, 'ST', 'STP', 'SAO TOME E PRINCIPE', 448, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (195, 'SN', 'SEN', 'SENEGAL', 450, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (196, 'RS', 'SRB', 'SERBIA', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (197, 'SC', 'SYC', 'SEYCHELLES', 449, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (198, 'SL', 'SLE', 'SIERRA LEONE', 451, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (199, 'SG', 'SGP', 'SINGAPORE', 346, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (200, 'SY', 'SYR', 'SIRIA', 348, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (201, 'SK', 'SVK', 'SLOVACCHIA', 255, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (202, 'SI', 'SVN', 'SLOVENIA', 251, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (203, 'SO', 'SOM', 'SOMALIA', 453, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (204, 'ES', 'ESP', 'SPAGNA', 239, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (205, 'LK', 'LKA', 'SRI LANKA', 311, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (206, 'FM', 'FSM', 'STATI FEDERATI DELLA MICRONESIA', 713, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (207, 'US', 'USA', 'STATI UNITI D''AMERICA', 536, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (208, 'ZA', 'ZAF', 'SUD AFRICA', 454, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (209, 'GS', 'SGS', 'SUD GEORGIA E ISOLE SANDWICH', 360, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (210, 'SD', 'SDN', 'SUDAN', 455, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (211, 'SR', 'SUR', 'SURINAME', 616, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (212, 'SJ', 'SJM', 'SVALBARD E JAN MAYEN', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (213, 'SE', 'SWE', 'SVEZIA', 240, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (214, 'CH', 'CHE', 'SVIZZERA', 241, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (215, 'SZ', 'SWZ', 'SWAZILAND', 456, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (216, 'TJ', 'TJK', 'TAGIKISTAN', 362, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (217, 'TH', 'THA', 'TAILANDIA', 349, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (218, 'TW', 'TWN', 'TAIWAN', 363, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (219, 'TZ', 'TZA', 'TANZANIA', 457, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (220, 'IO', 'IOT', 'TERRITORI BRITANNICI DELL''OCEANO INDIANO', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (221, 'TF', 'ATF', 'TERRITORI FRANCESI DEL SUD', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (222, 'PS', 'PSE', 'TERRITORI PALESTINESI OCCUPATI', 324, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (223, 'TL', 'TLS', 'TIMOR EST', 338, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (224, 'TG', 'TGO', 'TOGO', 458, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (225, 'TK', 'TKL', 'TOKELAU', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (226, 'TO', 'TON', 'TONGA', 730, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (227, 'TT', 'TTO', 'TRINIDAD E TOBAGO', 617, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (228, 'TN', 'TUN', 'TUNISIA', 460, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (229, 'TR', 'TUR', 'TURCHIA', 351, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (230, 'TM', 'TKM', 'TURKMENISTAN', 364, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (231, 'TV', 'TUV', 'TUVALU', 731, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (232, 'UA', 'UKR', 'UCRAINA', 243, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (233, 'UG', 'UGA', 'UGANDA', 461, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (234, 'HU', 'HUN', 'UNGHERIA', 244, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (235, 'UY', 'URY', 'URUGUAY', 618, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (236, 'UZ', 'UZB', 'UZBEKISTAN', 357, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (237, 'VU', 'VUT', 'VANUATU', 732, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (238, 'VE', 'VEN', 'VENEZUELA', 619, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (239, 'VN', 'VNM', 'VIETNAM', 353, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (240, 'WF', 'WLF', 'WALLIS E FUTUNA', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (241, 'YE', 'YEM', 'YEMEN', 354, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (242, 'ZM', 'ZMB', 'ZAMBIA', 464, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_NAZIONE
   (ID, CODICE_ISO, CODICE_ISO_3, DESCRIZIONE, CODICE_ISTAT, 
    DATA_INIZIO_VALIDITA)
 Values
   (243, 'ZW', 'ZWE', 'ZIMBABWE', 465, 
    TO_DATE('01/01/1900', 'DD/MM/YYYY'));
COMMIT;
