-- Al termine delle insert è necessario portare il valore corrente della sequence costruita su ID al valore massimo
SET DEFINE OFF;
Insert into SPENDING_PHA.MDS_A_REGIONE
   (ID, CODICE, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (1, 10, 'PIEMONTE', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_REGIONE
   (ID, CODICE, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (2, 20, 'VALLE D''AOSTA', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_REGIONE
   (ID, CODICE, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (3, 30, 'LOMBARDIA', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_REGIONE
   (ID, CODICE, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (4, 41, 'PROVINCIA AUTONOMA DI BOLZANO', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_REGIONE
   (ID, CODICE, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (5, 42, 'PROVINCIA AUTONOMA DI TRENTO', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_REGIONE
   (ID, CODICE, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (6, 50, 'VENETO', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_REGIONE
   (ID, CODICE, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (7, 60, 'FRIULI VENEZIA GIULIA', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_REGIONE
   (ID, CODICE, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (8, 70, 'LIGURIA', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_REGIONE
   (ID, CODICE, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (9, 80, 'EMILIA ROMAGNA', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_REGIONE
   (ID, CODICE, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (10, 90, 'TOSCANA', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_REGIONE
   (ID, CODICE, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (11, 100, 'UMBRIA', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_REGIONE
   (ID, CODICE, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (12, 110, 'MARCHE', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_REGIONE
   (ID, CODICE, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (13, 120, 'LAZIO', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_REGIONE
   (ID, CODICE, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (14, 130, 'ABRUZZO', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_REGIONE
   (ID, CODICE, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (15, 140, 'MOLISE', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_REGIONE
   (ID, CODICE, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (16, 150, 'CAMPANIA', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_REGIONE
   (ID, CODICE, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (17, 160, 'PUGLIA', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_REGIONE
   (ID, CODICE, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (18, 170, 'BASILICATA', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_REGIONE
   (ID, CODICE, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (19, 180, 'CALABRIA', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_REGIONE
   (ID, CODICE, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (20, 190, 'SICILIA', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_REGIONE
   (ID, CODICE, DESCRIZIONE, DATA_INIZIO_VALIDITA)
 Values
   (21, 200, 'SARDEGNA', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
COMMIT;
