-- Al termine delle insert è necessario portare il valore corrente della sequence costruita su ID al valore massimo
SET DEFINE OFF;
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (1, 1, 'TORINO', 'TO', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (2, 2, 'VERCELLI', 'VC', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (3, 3, 'NOVARA', 'NO', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (4, 4, 'CUNEO', 'CN', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (5, 5, 'ASTI', 'AT', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (6, 6, 'ALESSANDRIA', 'AL', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (7, 96, 'BIELLA', 'BI', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (8, 103, 'VERBANO-CUSIO-OSSOLA', 'VB', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (9, 7, 'VALLE D''AOSTA/VALLŽE D''AOSTE', 'AO', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (10, 12, 'VARESE', 'VA', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (11, 13, 'COMO', 'CO', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (12, 14, 'SONDRIO', 'SO', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (13, 15, 'MILANO', 'MI', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (14, 16, 'BERGAMO', 'BG', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (15, 17, 'BRESCIA', 'BS', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (16, 18, 'PAVIA', 'PV', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (17, 19, 'CREMONA', 'CR', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (18, 20, 'MANTOVA', 'MN', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (19, 97, 'LECCO', 'LC', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (20, 98, 'LODI', 'LO', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (21, 108, 'MONZA E DELLA BRIANZA', 'MB', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (22, 21, 'BOLZANO/BOZEN', 'BZ', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (23, 22, 'TRENTO', 'TN', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (24, 23, 'VERONA', 'VR', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (25, 24, 'VICENZA', 'VI', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (26, 25, 'BELLUNO', 'BL', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (27, 26, 'TREVISO', 'TV', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (28, 27, 'VENEZIA', 'VE', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (29, 28, 'PADOVA', 'PD', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (30, 29, 'ROVIGO', 'RO', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (31, 30, 'UDINE', 'UD', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (32, 93, 'PORDENONE', 'PN', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (33, 8, 'IMPERIA', 'IM', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (34, 9, 'SAVONA', 'SV', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (35, 10, 'GENOVA', 'GE', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (36, 11, 'LA SPEZIA', 'SP', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (37, 33, 'PIACENZA', 'PC', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (38, 34, 'PARMA', 'PR', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (39, 35, 'REGGIO NELL''EMILIA', 'RE', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (40, 37, 'BOLOGNA', 'BO', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (41, 40, 'FORL“-CESENA', 'FC', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (42, 99, 'RIMINI', 'RN', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (43, 45, 'MASSA-CARRARA', 'MS', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (44, 46, 'LUCCA', 'LU', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (45, 47, 'PISTOIA', 'PT', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (46, 48, 'FIRENZE', 'FI', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (47, 50, 'PISA', 'PI', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (48, 51, 'AREZZO', 'AR', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (49, 53, 'GROSSETO', 'GR', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (50, 54, 'PERUGIA', 'PG', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (51, 55, 'TERNI', 'TR', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (52, 41, 'PESARO E URBINO', 'PU', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (53, 42, 'ANCONA', 'AN', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (54, 43, 'MACERATA', 'MC', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (55, 44, 'ASCOLI PICENO', 'AP', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (56, 56, 'VITERBO', 'VT', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (57, 57, 'RIETI', 'RI', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (58, 58, 'ROMA', 'RM', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (59, 60, 'FROSINONE', 'FR', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (60, 66, 'L''AQUILA', 'AQ', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (61, 67, 'TERAMO', 'TE', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (62, 68, 'PESCARA', 'PE', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (63, 69, 'CHIETI', 'CH', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (64, 70, 'CAMPOBASSO', 'CB', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (65, 94, 'ISERNIA', 'IS', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (66, 61, 'CASERTA', 'CE', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (67, 62, 'BENEVENTO', 'BN', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (68, 63, 'NAPOLI', 'NA', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (69, 64, 'AVELLINO', 'AV', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (70, 65, 'SALERNO', 'SA', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (71, 71, 'FOGGIA', 'FG', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (72, 72, 'BARI', 'BA', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (73, 74, 'BRINDISI', 'BR', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (74, 75, 'LECCE', 'LE', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (75, 76, 'POTENZA', 'PZ', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (76, 77, 'MATERA', 'MT', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (77, 78, 'COSENZA', 'CS', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (78, 79, 'CATANZARO', 'CZ', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (79, 80, 'REGGIO CALABRIA', 'RC', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (80, 101, 'CROTONE', 'KR', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (81, 102, 'VIBO VALENTIA', 'VV', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (82, 82, 'PALERMO', 'PA', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (83, 83, 'MESSINA', 'ME', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (84, 84, 'AGRIGENTO', 'AG', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (85, 86, 'ENNA', 'EN', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (86, 87, 'CATANIA', 'CT', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (87, 89, 'SIRACUSA', 'SR', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (88, 90, 'SASSARI', 'SS', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (89, 91, 'NUORO', 'NU', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (90, 95, 'ORISTANO', 'OR', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (91, 111, 'SUD SARDEGNA', '-', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (92, 32, 'TRIESTE', 'TS', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (93, 31, 'GORIZIA', 'GO', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (94, 36, 'MODENA', 'MO', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (95, 38, 'FERRARA', 'FE', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (96, 39, 'RAVENNA', 'RA', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (97, 100, 'PRATO', 'PO', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (98, 49, 'LIVORNO', 'LI', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (99, 52, 'SIENA', 'SI', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (100, 109, 'FERMO', 'FM', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (101, 59, 'LATINA', 'LT', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (102, 110, 'BARLETTA - ANDRIA - TRANI', 'BT', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (103, 73, 'TARANTO', 'TA', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (104, 85, 'CALTANISSETTA', 'CL', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (105, 88, 'RAGUSA', 'RG', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (106, 81, 'TRAPANI', 'TP', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (107, 104, 'OLBIA - TEMPIO', 'OT', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (108, 92, 'CAGLIARI', 'CA', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (109, 105, 'OGLIASTRA', 'OG', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (110, 106, 'MEDIO CAMPIDANO', 'VS', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
Insert into SPENDING_PHA.MDS_A_PROVINCIA
   (ID, CODICE, DESCRIZIONE, SIGLA, DATA_INIZIO_VALIDITA)
 Values
   (111, 107, 'CARBONIA - IGLESIAS', 'CI', TO_DATE('01/01/1900', 'DD/MM/YYYY'));
COMMIT;
