CREATE TABLE SPENDING_PHA.BATCH_JOB_EXECUTION
(
  JOB_EXECUTION_ID            NUMBER(19)        NOT NULL,
  VERSION                     NUMBER(19),
  JOB_INSTANCE_ID             NUMBER(19)        NOT NULL,
  CREATE_TIME                 TIMESTAMP(6)      NOT NULL,
  START_TIME                  TIMESTAMP(6),
  END_TIME                    TIMESTAMP(6),
  STATUS                      VARCHAR2(10 BYTE),
  EXIT_CODE                   VARCHAR2(2500 BYTE),
  EXIT_MESSAGE                VARCHAR2(2500 BYTE),
  LAST_UPDATED                TIMESTAMP(6),
  JOB_CONFIGURATION_LOCATION  VARCHAR2(2500 BYTE)
);


CREATE UNIQUE INDEX SPENDING_PHA.SYS_C00250425 ON SPENDING_PHA.BATCH_JOB_EXECUTION
(JOB_EXECUTION_ID);

ALTER TABLE SPENDING_PHA.BATCH_JOB_EXECUTION ADD (
  CONSTRAINT SYS_C00250425
  PRIMARY KEY
  (JOB_EXECUTION_ID)
  USING INDEX;
  ENABLE VALIDATE);

ALTER TABLE SPENDING_PHA.BATCH_JOB_EXECUTION ADD (
  CONSTRAINT JOB_INST_EXEC_FK 
  FOREIGN KEY (JOB_INSTANCE_ID) 
  REFERENCES SPENDING_PHA.BATCH_JOB_INSTANCE (JOB_INSTANCE_ID)
  ENABLE VALIDATE);