CREATE TABLE SPENDING_PHA.BATCH_JOB_EXECUTION_CONTEXT
(
  JOB_EXECUTION_ID    NUMBER(19)                NOT NULL,
  SHORT_CONTEXT       VARCHAR2(2500 BYTE)       NOT NULL,
  SERIALIZED_CONTEXT  CLOB
);


CREATE UNIQUE INDEX SPENDING_PHA.SYS_C00250445 ON SPENDING_PHA.BATCH_JOB_EXECUTION_CONTEXT
(JOB_EXECUTION_ID);

ALTER TABLE SPENDING_PHA.BATCH_JOB_EXECUTION_CONTEXT ADD (
  CONSTRAINT SYS_C00250445
  PRIMARY KEY
  (JOB_EXECUTION_ID)
  USING INDEX
  ENABLE VALIDATE);

ALTER TABLE SPENDING_PHA.BATCH_JOB_EXECUTION_CONTEXT ADD (
  CONSTRAINT JOB_EXEC_CTX_FK 
  FOREIGN KEY (JOB_EXECUTION_ID) 
  REFERENCES SPENDING_PHA.BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
  ENABLE VALIDATE);