CREATE TABLE SPENDING_PHA.BATCH_STEP_EXECUTION_CONTEXT
(
  STEP_EXECUTION_ID   NUMBER(19)                NOT NULL,
  SHORT_CONTEXT       VARCHAR2(2500 BYTE)       NOT NULL,
  SERIALIZED_CONTEXT  CLOB
);


CREATE UNIQUE INDEX SPENDING_PHA.SYS_C00250441 ON SPENDING_PHA.BATCH_STEP_EXECUTION_CONTEXT
(STEP_EXECUTION_ID);

ALTER TABLE SPENDING_PHA.BATCH_STEP_EXECUTION_CONTEXT ADD (
  CONSTRAINT SYS_C00250441
  PRIMARY KEY
  (STEP_EXECUTION_ID)
  USING INDEX
  ENABLE VALIDATE);

ALTER TABLE SPENDING_PHA.BATCH_STEP_EXECUTION_CONTEXT ADD (
  CONSTRAINT STEP_EXEC_CTX_FK 
  FOREIGN KEY (STEP_EXECUTION_ID) 
  REFERENCES SPENDING_PHA.BATCH_STEP_EXECUTION (STEP_EXECUTION_ID)
  ENABLE VALIDATE);