CREATE TABLE SPENDING_PHA.BATCH_JOB_EXECUTION_PARAMS
(
  JOB_EXECUTION_ID  NUMBER(19)                  NOT NULL,
  TYPE_CD           VARCHAR2(6 BYTE)            NOT NULL,
  KEY_NAME          VARCHAR2(100 BYTE)          NOT NULL,
  STRING_VAL        VARCHAR2(250 BYTE),
  DATE_VAL          TIMESTAMP(6),
  LONG_VAL          NUMBER(19),
  DOUBLE_VAL        NUMBER,
  IDENTIFYING       CHAR(1 BYTE)                NOT NULL
);


ALTER TABLE SPENDING_PHA.BATCH_JOB_EXECUTION_PARAMS ADD (
  CONSTRAINT JOB_EXEC_PARAMS_FK 
  FOREIGN KEY (JOB_EXECUTION_ID) 
  REFERENCES SPENDING_PHA.BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
  ENABLE VALIDATE);