CREATE TABLE SPENDING_PHA.MEF_DATI_RIEPILOGO_FATTURA
(
  ID                     VARCHAR2(255 CHAR)     NOT NULL,
  IMPORT_DATE            TIMESTAMP(6),
  ALIQUOTAIVA            NUMBER(19,2),
  ARROTONDAMENTO         NUMBER(19,2),
  ESIGIBILITAIVA         VARCHAR2(255 CHAR),
  IMPONIBILE_IMPORTO     NUMBER(19,2),
  IMPOSTA                NUMBER(19,2),
  NATURA                 VARCHAR2(255 CHAR),
  RIFERIMENTO_NORMATIVO  VARCHAR2(255 CHAR),
  SPESE_ACCESSORIE       NUMBER(19,2),
  INVOICE_ID             VARCHAR2(255 CHAR)
);


CREATE UNIQUE INDEX SPENDING_PHA.DATI_RIEPILOGOPK ON SPENDING_PHA.MEF_DATI_RIEPILOGO_FATTURA
(ID);

ALTER TABLE SPENDING_PHA.MEF_DATI_RIEPILOGO_FATTURA ADD (
  CONSTRAINT DATI_RIEPILOGOPK
  PRIMARY KEY
  (ID)
  USING INDEX SPENDING_PHA.DATI_RIEPILOGOPK
  ENABLE VALIDATE);

ALTER TABLE SPENDING_PHA.MEF_DATI_RIEPILOGO_FATTURA ADD (
  CONSTRAINT FKBSAXN93M19TA6ONB54K9JQ03F 
  FOREIGN KEY (INVOICE_ID) 
  REFERENCES SPENDING_PHA.MEF_FATTURA (ID)
  ENABLE VALIDATE);