CREATE TABLE SPENDING_PHA.MEF_DOC_CORRELATO_FATTURA
(
  ID                           VARCHAR2(255 CHAR) NOT NULL,
  IMPORT_DATE                  TIMESTAMP(6),
  CIG_CODE                     VARCHAR2(255 CHAR),
  CODICECUP                    VARCHAR2(255 CHAR),
  CODICE_COMMESSA_CONVENZIONE  VARCHAR2(255 CHAR),
  DATA                         DATE,
  DOCUMENT_ID                  VARCHAR2(255 CHAR),
  DOCUMENTO_CORRELATO_TYPE     VARCHAR2(255 CHAR),
  NUM_ITEM                     VARCHAR2(255 CHAR),
  INVOICE_ID                   VARCHAR2(255 CHAR)
);


CREATE UNIQUE INDEX SPENDING_PHA.DOCUMENTO_CORRELATOPK ON SPENDING_PHA.MEF_DOC_CORRELATO_FATTURA
(ID);

ALTER TABLE SPENDING_PHA.MEF_DOC_CORRELATO_FATTURA ADD (
  CONSTRAINT DOCUMENTO_CORRELATOPK
  PRIMARY KEY
  (ID)
  USING INDEX SPENDING_PHA.DOCUMENTO_CORRELATOPK
  ENABLE VALIDATE);

ALTER TABLE SPENDING_PHA.MEF_DOC_CORRELATO_FATTURA ADD (
  CONSTRAINT FKHNW9ML89FGCFU6GWF8VEL6U5K 
  FOREIGN KEY (INVOICE_ID) 
  REFERENCES SPENDING_PHA.MEF_FATTURA (ID)
  ENABLE VALIDATE);