CREATE TABLE SPENDING_PHA.MEF_SOGGETTO_PART_FATTURA
(
  ID                             VARCHAR2(255 CHAR) NOT NULL,
  IMPORT_DATE                    TIMESTAMP(6),
  ADMINISTRATIVE_REFERENCE       VARCHAR2(255 CHAR),
  CITY                           VARCHAR2(255 CHAR),
  CLEARANCE_STATE                VARCHAR2(255 CHAR),
  COUNTRY                        VARCHAR2(255 CHAR),
  DISTRICT                       VARCHAR2(255 CHAR),
  EMAIL_ADDRESS                  VARCHAR2(255 CHAR),
  EORI_CODE                      VARCHAR2(255 CHAR),
  FAX_NUMBER                     VARCHAR2(255 CHAR),
  FIRST_NAME                     VARCHAR2(255 CHAR),
  HOUSE_NUMBER                   VARCHAR2(255 CHAR),
  LAST_NAME                      VARCHAR2(255 CHAR),
  NAME                           VARCHAR2(255 CHAR),
  NUMERO_LICENZA_GUIDA           VARCHAR2(255 CHAR),
  PERM_EST_CITY                  VARCHAR2(255 CHAR),
  PERM_EST_COUNTRY               VARCHAR2(255 CHAR),
  PERM_EST_DISTRICT              VARCHAR2(255 CHAR),
  PERM_EST_HOUSE_NUMBER          VARCHAR2(255 CHAR),
  PERM_EST_STREET_ADDRESS        VARCHAR2(255 CHAR),
  PERM_EST_ZIP_CODE              VARCHAR2(255 CHAR),
  PHONE_NUMBER                   VARCHAR2(255 CHAR),
  PROFESSIONAL_REG               VARCHAR2(255 CHAR),
  PROFESSIONAL_REG_DISTRICT      VARCHAR2(255 CHAR),
  PROFESSIONAL_REG_NUMBER        VARCHAR2(255 CHAR),
  PROFESSIONAL_REG_SUBSCR_DATE   DATE,
  REA_NUMBER                     VARCHAR2(255 CHAR),
  REA_OFFICE                     VARCHAR2(255 CHAR),
  SHARE_CAPITAL                  NUMBER(19,2),
  SOCIAL_SECURITY_NUMBER         VARCHAR2(255 CHAR),
  SOLE_STAKEHOLDER               VARCHAR2(255 CHAR),
  STREET_ADDRESS                 VARCHAR2(255 CHAR),
  TAX_CODE                       VARCHAR2(255 CHAR),
  TAX_COUNTRY_CODE               VARCHAR2(255 CHAR),
  TAX_REPRESENTATIVE_COUNTRY_ID  VARCHAR2(255 CHAR),
  TAX_REPRESENTATIVE_FIRST_NAME  VARCHAR2(255 CHAR),
  TAX_REPRESENTATIVE_ID_CODE     VARCHAR2(255 CHAR),
  TAX_REPRESENTATIVE_LAST_NAME   VARCHAR2(255 CHAR),
  TAX_REPRESENTATIVE_NAME        VARCHAR2(255 CHAR),
  TAX_SYSTEM                     VARCHAR2(255 CHAR),
  TITLE                          VARCHAR2(255 CHAR),
  TYPE                           VARCHAR2(255 CHAR),
  ZIP_CODE                       VARCHAR2(255 CHAR),
  INVOICE_ID                     VARCHAR2(255 CHAR)
);


CREATE UNIQUE INDEX SPENDING_PHA.INVOICE_PARTICIPANTPK ON SPENDING_PHA.MEF_SOGGETTO_PART_FATTURA
(ID);

ALTER TABLE SPENDING_PHA.MEF_SOGGETTO_PART_FATTURA ADD (
  CONSTRAINT INVOICE_PARTICIPANTPK
  PRIMARY KEY
  (ID)
  USING INDEX SPENDING_PHA.INVOICE_PARTICIPANTPK
  ENABLE VALIDATE);

ALTER TABLE SPENDING_PHA.MEF_SOGGETTO_PART_FATTURA ADD (
  CONSTRAINT FK1R1U0BDSVTBEIUTUAVX13GMNR 
  FOREIGN KEY (INVOICE_ID) 
  REFERENCES SPENDING_PHA.MEF_FATTURA (ID)
  ENABLE VALIDATE);