CREATE TABLE SPENDING_PHA.MEF_ALLEGATO_FATTURA
(
  ID                     VARCHAR2(255 CHAR)     NOT NULL,
  IMPORT_DATE            TIMESTAMP(6),
  COMPRESSION_ALGORITHM  VARCHAR2(255 CHAR),
  DATA                   BLOB,
  DESCRIPTION            CLOB,
  FORMAT                 VARCHAR2(255 CHAR),
  NAME                   VARCHAR2(255 CHAR),
  INVOICE_ID             VARCHAR2(255 CHAR)
);


CREATE UNIQUE INDEX SPENDING_PHA.ATTACHMENTPK ON SPENDING_PHA.MEF_ALLEGATO_FATTURA
(ID);

ALTER TABLE SPENDING_PHA.MEF_ALLEGATO_FATTURA ADD (
  CONSTRAINT ATTACHMENTPK
  PRIMARY KEY
  (ID)
  USING INDEX SPENDING_PHA.ATTACHMENTPK
  ENABLE VALIDATE);

ALTER TABLE SPENDING_PHA.MEF_ALLEGATO_FATTURA ADD (
  CONSTRAINT FKAPETYEV9J9MLNDTDPJY0MHEVL 
  FOREIGN KEY (INVOICE_ID) 
  REFERENCES SPENDING_PHA.MEF_FATTURA (ID)
  ENABLE VALIDATE);